/* Keep logging, reusable exercises and program editing in separate views. */
function favoriteExercises(){const lib=ensureLibraryProfile();return (lib.favorites||[]).map(id=>availableExercises().find(e=>e.id===id)).filter(Boolean);}
function renderFavorites(){const list=document.getElementById('favoriteExerciseList');if(!list)return;const t=smoothText;
 list.innerHTML=favoriteExercises().map(e=>`<div class="favorite-row"><strong translate="no">${esc(e.name)}</strong><button type="button" class="button secondary" data-use-favorite="${esc(e.id)}">${t('Log','Log')}</button><button type="button" class="text-button" data-remove-favorite="${esc(e.id)}">${t('Fjern','Remove')}</button></div>`).join('')||`<p class="foot">${t('Gem de øvelser, du ofte bruger. Tryk derefter Log, og indtast dine sæt og kg.','Save exercises you use often. Then tap Log and enter your sets and weight.')}</p>`;
 const select=document.getElementById('favoriteExerciseChoice'),prev=select.value;select.innerHTML=availableExercises().map(e=>`<option value="${esc(e.id)}">${esc(e.name)}</option>`).join('');if(availableExercises().some(e=>e.id===prev))select.value=prev;
}
const clearWorkoutBase=renderWorkout;
renderWorkout=function(){clearWorkoutBase();renderFavorites();};
const clearOpenProgramBase=openManagedProgram;
openManagedProgram=function(id){clearOpenProgramBase(id);selectProgramView('manage');document.getElementById('workoutEditor').scrollIntoView({block:'start',behavior:'smooth'});};
const clearDashboardBase=renderDashboard;
renderDashboard=function(){clearDashboardBase();const agenda=document.getElementById('sevenDayAgenda');if(!agenda)return;
 const add=document.createElement('button');add.type='button';add.className='button secondary full';add.dataset.quickActivity=today();add.textContent=smoothText('+ Tilføj aktivitet','+ Add activity');agenda.querySelector('.card-top').after(add);
 agenda.querySelectorAll('.agenda-day').forEach(button=>{const row=document.createElement('div');row.className='agenda-action-row';button.before(row);row.append(button);const plus=document.createElement('button');plus.type='button';plus.className='agenda-add';plus.dataset.quickActivity=button.dataset.historyDate;plus.textContent='+';plus.setAttribute('aria-label',smoothText('Tilføj aktivitet ','Add activity ')+dateText(button.dataset.historyDate));row.append(plus);});
};
function openQuickActivity(date){const f=document.getElementById('quickActivityForm');f.reset();f.elements.date.value=date;f.elements.time.value='18:00';f.elements.endTime.value='19:00';document.getElementById('quickActivityError').textContent='';document.getElementById('quickActivityDialog').showModal();}
document.addEventListener('DOMContentLoaded',()=>{
 const t=smoothText,train=document.getElementById('train'),manager=train.querySelector('[data-program-panel=manage]'),nav=train.querySelector('.program-navigation');
 nav.querySelector('[data-program-view=train]').textContent=t('Træning','Training');const tab=document.createElement('button');tab.type='button';tab.dataset.programView='favorites';tab.textContent=t('Faste øvelser','Saved exercises');nav.insertBefore(tab,nav.lastElementChild);
 const editor=document.getElementById('workoutEditor');manager.prepend(editor);editor.open=false;
 const createCard=manager.querySelector('.new-program-card'),createDetails=document.createElement('details');createDetails.className='program-create-toggle';createDetails.innerHTML=`<summary>+ ${t('Opret program','Create workout')}</summary>`;createCard.before(createDetails);createDetails.append(createCard);
 document.querySelector('.manage-programs').hidden=true;document.getElementById('planHint').hidden=true;document.querySelector('#train .eyebrow').hidden=true;
 const quick=document.getElementById('quickAddExercise');quick.textContent=t('Redigér dette program','Edit this workout');quick.addEventListener('click',()=>{selectProgramView('manage');editor.open=true;editor.scrollIntoView({block:'start'});});
 const lower=document.getElementById('liftForm').closest('.two');[...lower.children].forEach((card,i)=>{const details=document.createElement('details');details.className='training-fold';details.id=i===0?'singleExerciseFold':'recentTrainingFold';details.innerHTML=`<summary>${i===0?t('Log en enkelt øvelse','Log a single exercise'):t('Se seneste træning','Recent training')}</summary>`;card.before(details);details.append(card);if(card.tagName==='DETAILS'){card.open=true;card.querySelector('summary').hidden=true;}card.querySelector('h2').hidden=true;});
 const favorite=document.createElement('div');favorite.dataset.programPanel='favorites';favorite.hidden=true;favorite.innerHTML=`<article class="card"><h2>${t('Faste øvelser','Saved exercises')}</h2><div id="favoriteExerciseList"></div></article><article class="card"><h2>${t('Gem en øvelse','Save an exercise')}</h2><form id="favoriteExerciseForm"><label class="field">${t('Vælg fra biblioteket','Choose from the library')}<select id="favoriteExerciseChoice"></select></label><button class="button secondary full">+ ${t('Gem som fast øvelse','Save exercise')}</button></form><details class="training-fold"><summary>+ ${t('Opret din egen øvelse','Create your own exercise')}</summary><form id="newFavoriteForm"><label class="field">${t('Navn på øvelse','Exercise name')}<input name="name" required maxlength="100" placeholder="Fx squat"></label><button class="button full">${t('Gem fast øvelse','Save exercise')}</button><p id="favoriteError" role="alert" class="foot"></p></form></details></article>`;train.append(favorite);
 document.getElementById('favoriteExerciseForm').addEventListener('submit',e=>{e.preventDefault();const lib=ensureLibraryProfile(),id=document.getElementById('favoriteExerciseChoice').value;if(!id)return;lib.favorites=[...new Set([...(lib.favorites||[]),id])];save();});
 document.getElementById('newFavoriteForm').addEventListener('submit',e=>{e.preventDefault();try{const name=libraryName(e.target.elements.name.value),exercise=availableExercises().find(x=>x.name.toLowerCase()===name.toLowerCase())||createPrivateExercise(name),lib=ensureLibraryProfile();lib.favorites=[...new Set([...(lib.favorites||[]),exercise.id])];save();e.target.reset();document.getElementById('favoriteError').textContent='';}catch(err){document.getElementById('favoriteError').textContent=err.message;}});
 const dialog=document.createElement('dialog');dialog.id='quickActivityDialog';dialog.innerHTML=`<div class="card-top"><h2>${t('Tilføj aktivitet','Add activity')}</h2><button type="button" id="closeQuickActivity" class="icon-button" aria-label="${t('Luk','Close')}">×</button></div><form id="quickActivityForm" class="form"><label class="field span">${t('Hvad skal du?','Activity')}<select name="type"><option value="Styrke">${t('Styrketræning','Strength training')}</option><option value="Kamp">${t('Kamp','Match')}</option><option value="Sportstræning">${t('Sportstræning','Sports training')}</option></select></label><label class="field span">${t('Dato','Date')}<input name="date" type="date" required></label><label class="field">${t('Start','Start')}<input name="time" type="time" required></label><label class="field">${t('Slut','End')}<input name="endTime" type="time" required></label><label class="field span"><span><input name="endsNextDay" type="checkbox"> ${t('Slutter næste dag','Ends the next day')}</span></label><label class="field span">${t('Navn (valgfrit)','Name (optional)')}<input name="title" maxlength="100" placeholder="${t('Fx Upper A eller modstander','E.g. Upper A or opponent')}"></label><p id="quickActivityError" role="alert" class="foot span"></p><button class="button span">${t('Gem aktivitet','Save activity')}</button></form>`;document.body.append(dialog);
 document.getElementById('closeQuickActivity').onclick=()=>dialog.close();document.getElementById('quickActivityForm').addEventListener('submit',e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target)),error=activityTimingError(o.time,o.endTime,!!o.endsNextDay);if(error){document.getElementById('quickActivityError').textContent=error;return;}data.events.push({...o,id:crypto.randomUUID(),title:libraryName(o.title)||o.type,endsNextDay:!!o.endsNextDay});save();dialog.close();toast(t('Aktivitet gemt','Activity saved'));});render();
});
document.addEventListener('click',e=>{
 const add=e.target.closest('[data-quick-activity]');if(add)openQuickActivity(add.dataset.quickActivity);
 const remove=e.target.closest('[data-remove-favorite]');if(remove){const lib=ensureLibraryProfile();lib.favorites=(lib.favorites||[]).filter(id=>id!==remove.dataset.removeFavorite);save();}
 const use=e.target.closest('[data-use-favorite]');if(use){const exercise=availableExercises().find(x=>x.id===use.dataset.useFavorite);if(!exercise)return;selectProgramView('train');const fold=document.getElementById('singleExerciseFold'),form=document.getElementById('liftForm');fold.open=true;form.reset();form.elements.exercise.value=exercise.name;fold.scrollIntoView({block:'center',behavior:'smooth'});form.elements.kg.focus({preventScroll:true});}
});
