Object.assign(EN,{'Dato for madlog':'Date for food log','Al mad, du logger, bliver gemt på denne dato.':'All food you log is saved on this date.','Log mad på denne dag':'Log food for this day','Ingen måltider registreret på denne dato.':'No meals recorded on this date.'});
function dayCounts(date){return {meals:data.meals.filter(x=>x.date===date).length,lifts:data.lifts.filter(x=>x.date===date).length,events:data.events.filter(x=>x.date===date).length,recovery:data.recovery[date]?1:0};}
function dayCountLabel(date){const c=dayCounts(date),logs=c.meals+c.lifts+c.recovery;return {logs,planned:c.events};}
const dayDashboardBase=renderDashboard;
renderDashboard=function(){dayDashboardBase();const start=weekStart(overviewDate);document.getElementById('dashboardWeek').innerHTML=Array.from({length:7},(_,i)=>{const date=shiftDate(start,i),c=dayCountLabel(date),en=appLanguage()==='en';return `<button type="button" class="week-dot day-tile ${date===overviewDate?'current':''} ${c.logs||c.planned?'populated':''}" data-history-date="${date}" aria-pressed="${date===overviewDate}" aria-label="${esc(historyLabel(date))}: ${c.logs} logs, ${c.planned} ${en?'planned':'planlagte'}"><span>${new Date(date+'T12:00:00').toLocaleDateString(appLocale(),{weekday:'short'})}</span><strong>${Number(date.slice(-2))}</strong><small>${c.logs?c.logs+' logs':en?'No logs':'Ingen logs'}</small>${c.planned?`<small>${c.planned} ${en?'planned':'planlagt'}</small>`:''}</button>`;}).join('');};
const dayMonthBase=renderMonthCalendar;
renderMonthCalendar=function(){dayMonthBase();document.querySelectorAll('.month-day').forEach(button=>{const date=button.dataset.value,c=dayCountLabel(date),en=appLanguage()==='en';button.classList.toggle('populated',!!(c.logs||c.planned));button.innerHTML=`<strong>${Number(date.slice(-2))}</strong>${c.logs?`<small class="day-count">${c.logs} logs</small>`:''}${c.planned?`<small>${c.planned} ${en?'plan':'plan'}</small>`:''}`;button.setAttribute('aria-label',`${historyLabel(date)}: ${c.logs} logs, ${c.planned} ${en?'planned activities':'planlagte aktiviteter'}`);});};
function renderDatedMeals(){const list=document.getElementById('mealList');if(!document.getElementById('foodLogDate'))return;const date=foodLogDate(),meals=data.meals.filter(m=>m.date===date),en=appLanguage()==='en';list.previousElementSibling.textContent=(en?'Meals · ':'Måltider · ')+historyLabel(date);list.innerHTML=meals.map(m=>`<div class="history-log-row"><span translate="no">${esc(m.name)}<small>${esc(m.kcal)} kcal · ${esc(m.protein)} g protein</small></span><button type="button" class="text-button" data-action="remove" data-key="meals" data-value="${esc(m.id)}">${en?'Delete':'Slet'}</button></div>`).join('')||`<p class="foot">${en?'No meals recorded on this date.':'Ingen måltider registreret på denne dato.'}</p>`;document.getElementById('foodDateNotice').textContent=en?'All food you log is saved on this date.':'Al mad, du logger, bliver gemt på denne dato.';}
const dayRenderBase=render;
render=function(){dayRenderBase();renderDatedMeals();};
document.addEventListener('DOMContentLoaded',()=>{
 const bar=document.createElement('div');bar.className='food-date-card';bar.innerHTML=`<label class="field">Dato for madlog<input id="foodLogDate" type="date" max="${today()}" value="${today()}" required></label><p id="foodDateNotice" class="foot"></p>`;document.getElementById('fuel').prepend(bar);
 document.getElementById('foodLogDate').addEventListener('change',e=>{if(!historyDateValid(e.target.value)||e.target.value>today())e.target.value=today();renderDatedMeals();});
 const button=document.createElement('button');button.type='button';button.className='button secondary full';button.id='logFoodForDay';button.textContent='Log mad på denne dag';document.getElementById('recentActivity').after(button);
 button.addEventListener('click',()=>{if(overviewDate>today()){toast(appLanguage()==='en'?'Choose today or an earlier day':'Vælg i dag eller en tidligere dag');return;}document.getElementById('foodLogDate').value=overviewDate;showTab('fuel');selectFoodView('log');renderDatedMeals();window.scrollTo({top:0,behavior:'instant'});});
 render();
});
