/* Local-only daily planning and deliberate, reversible shortcuts. */
const flowText=(da,en)=>smoothText(da,en);
function weeklySummary(end=today()){
 const start=shiftDate(end,-6),rows=historySeries(data,start,end),logged=rows.filter(r=>r.count),weights=rows.filter(r=>r.weight!==null),lifts=data.lifts.filter(l=>l.date>=start&&l.date<=end);
 return {start,end,days:logged.length,average:logged.length?Math.round(logged.reduce((n,r)=>n+r.kcal,0)/logged.length):null,sessions:new Set(lifts.map(l=>l.date+'|'+(l.workout||'Andet pas'))).size,exercises:lifts.length,weights:weights.length,change:weights.length>=2?Math.round((weights.at(-1).weight-weights[0].weight)*10)/10:null,planned:data.events.filter(e=>e.date>=start&&e.date<=end).length};
}
function renderEveryday(){const daily=document.getElementById('dailyPlan');if(!daily)return;const date=overviewDate,t=flowText,events=data.events.filter(e=>e.date===date).slice().sort((a,b)=>String(a.time).localeCompare(String(b.time))),goal=date>=today()?currentKcalGoal(date):null;
 const timeline=[];events.forEach(e=>{timeline.push({time:e.time,title:e.title||e.type,detail:activityTimeLabel(e),event:e});if(e.type==='Kamp'){const times=matchMealTimes(e);[[times.meal,t('Spis før kampen','Pre-match meal'),t('Fx ris med kylling eller tofu','Try rice with chicken or tofu')],[times.snack,t('Lille snack, hvis du har brug for den','Small snack if needed'),t('Fx banan eller en bolle','Try a banana or bread roll')],[times.after,t('Mad efter kampen','Post-match food'),t('Fx sandwich og mælk','Try a sandwich and milk')]].forEach(([at,title,detail])=>{if(at&&localDate(at)===date&&!mealOverlapsGame(at))timeline.push({time:at.toTimeString().slice(0,5),title,detail});});}});
 timeline.sort((a,b)=>String(a.time).localeCompare(String(b.time)));
 daily.innerHTML=`<div class="card-top"><h2>${date===today()?t('Din plan i dag','Your plan today'):t('Din dagsplan','Your daily plan')}</h2><span class="foot">${esc(dateText(date))}</span></div>${goal?`<p class="daily-target">${t('Dagens energimål','Daily energy target')} <strong>${uiNumber(goal)} kcal</strong></p>`:''}${timeline.length?timeline.map(row=>`<div class="flow-timeline"><time>${esc(row.time||'—')}</time><div><strong>${esc(row.title)}</strong><small>${esc(row.detail)}</small></div>${row.event?.type==='Styrke'?`<button type="button" class="text-button" data-start-planned="${esc(row.event.id)}">${t('Åbn','Open')}</button>`:''}</div>`).join(''):`<p class="foot">${t('Ingen aktivitet planlagt. Tilføj dagens træning, eller brug dagen til restitution.','No activity planned. Add training or use today for recovery.')}</p>`}<div class="flow-actions"><button type="button" class="button secondary" data-quick-activity="${date}">+ ${t('Aktivitet','Activity')}</button><button type="button" class="button secondary" data-flow-meal="${date}" ${date>today()?'disabled':''}>+ ${t('Log mad','Log food')}</button></div>${events.some(e=>e.type==='Kamp')?`<p class="foot">${t('Madtider er forslag. Se portioner og alternativer under Mad på kampdag.','Food times are suggestions. See portions and alternatives in Match-day food.')}</p>`:''}`;
 const week=weeklySummary(date>today()?today():date),target=document.getElementById('weeklyReview'),open=target.querySelector('details')?.open;
 target.innerHTML=`<details ${open?'open':''}><summary>${t('Dit ugeoverblik','Your weekly review')} <small>${esc(dateText(week.start))} – ${esc(dateText(week.end))}</small></summary><div class="flow-week-grid"><div><strong>${week.sessions}</strong><span>${t('styrkepas med logs','workouts with logs')}</span></div><div><strong>${week.days}/7</strong><span>${t('dage med madlogs','days with food logs')}</span></div><div><strong>${week.average===null?'—':uiNumber(week.average)}</strong><span>${t('kcal pr. registreret dag','kcal per logged day')}</span></div><div><strong>${week.change===null?'—':(week.change>0?'+':'')+uiNumber(week.change)+' kg'}</strong><span>${t('ændring mellem vejninger','change between weigh-ins')}</span></div></div><p class="foot">${week.planned} ${t('planlagte aktiviteter er ikke det samme som gennemførte.','planned activities are not the same as completed activities.')} ${week.days<7?t('Der mangler madlogs på','Food logs missing on')+' '+(7-week.days)+' '+t('dage.','days.'):t('Alle dage har mindst én madlog.','Each day has at least one food log.')} ${t('En madlog betyder ikke nødvendigvis, at hele dagen er registreret.','A food log does not necessarily mean the full day was recorded.')}</p><p class="foot">${week.weights<2?t('Vægtudvikling kræver mindst to vejninger på forskellige datoer i perioden.','Weight change needs weigh-ins on at least two dates in this period.'):t('Vægtændringen bygger på første og sidste vejning i perioden, ikke en beregnet muskelændring.','Weight change uses the first and last weigh-in, not an estimate of muscle gain.')}</p><button type="button" class="text-button" data-action="tab" data-value="progress">${t('Se grafer og længere perioder','See charts and longer periods')} →</button></details>`;
 renderShopping();
}
const everydayRenderBase=render;
render=function(){everydayRenderBase();renderEveryday();};
function previousLiftFor(form){const raw=personalPlans()[currentMode()]?.[workoutIndex]?.[1]?.[Number(form.dataset.index)];if(!raw)return null;const exercise=workoutExercise(raw).name,workout=personalPlans()[currentMode()][workoutIndex][0];return data.lifts.filter(l=>l.exercise===exercise&&l.workout===workout&&l.date<trainingDate).slice().sort((a,b)=>a.date.localeCompare(b.date)).at(-1)||null;}
const everydayWorkoutBase=renderWorkout;
renderWorkout=function(){everydayWorkoutBase();document.querySelectorAll('.exerciseForm').forEach(form=>{const last=previousLiftFor(form);if(!last)return;const button=document.createElement('button');button.type='button';button.className='text-button last-lift';button.dataset.previousLift='true';button.textContent=flowText('Brug sidste: ','Use last: ')+last.sets+' × '+last.reps+(last.kg!==''&&last.kg!=null?' · '+last.kg+' kg':'')+' · '+dateText(last.date);form.after(button);});};
let copiedMealIds=[];
function renderCopyMeals(){const f=document.getElementById('copyMealsForm'),date=f.elements.source.value,meals=data.meals.filter(m=>m.date===date);document.getElementById('copyMealChoices').innerHTML=meals.map(m=>`<label class="flow-check"><input type="checkbox" name="meal" value="${esc(m.id)}" checked><span>${esc(m.name)}<small>${esc(m.kcal)} kcal · ${esc(m.category||'')}</small></span></label>`).join('')||`<p class="foot">${flowText('Ingen måltider på denne dato.','No meals on this date.')}</p>`;f.querySelector('[type=submit]').disabled=!meals.length;}
function copyMeals(ids,source,target){if(!historyDateValid(source)||!historyDateValid(target)||target>today()||source===target)throw Error(flowText('Vælg to forskellige datoer, senest i dag.','Choose two different dates, no later than today.'));const rows=data.meals.filter(m=>m.date===source&&ids.includes(m.id));if(!rows.length)throw Error(flowText('Vælg mindst ét måltid.','Select at least one meal.'));const copies=rows.map(m=>({...m,id:crypto.randomUUID(),date:target}));data.meals.push(...copies);return copies.map(m=>m.id);}
function repetitionCandidates(event,count){return Array.from({length:count},(_,i)=>({...event,id:crypto.randomUUID(),date:shiftDate(event.date,7*(i+1)),repeatedFrom:event.id})).filter(candidate=>!data.events.some(e=>e.date===candidate.date&&e.time===candidate.time&&e.type===candidate.type&&e.title===candidate.title));}
function renderRepeatPreview(){const f=document.getElementById('repeatActivityForm'),event=data.events.find(e=>e.id===f.elements.event.value),count=Math.min(8,Math.max(1,Number(f.elements.count.value)||1));const rows=event?repetitionCandidates(event,count):[];document.getElementById('repeatPreview').textContent=rows.length?rows.map(e=>dateText(e.date)+' · '+activityTimeLabel(e)).join('\n'):flowText('Ingen nye datoer. Eksisterende identiske aktiviteter springes over.','No new dates. Existing identical activities are skipped.');}
function shoppingMeals(){return [...mealIdeas.map(m=>({...m,key:'idea:'+m.id})),...data.presets.map(m=>({...m,key:'preset:'+m.id}))];}
const shoppingRecipeDefaults={
 'idea:morgenmad0':['Havregryn','Mælk','Banan','Peanutbutter'],
 'idea:morgenmad1':['Rugbrød','Æg','Mælk'],
 'idea:morgenmad2':['Skyr','Müsli','Nødder','Bær'],
 'idea:morgenmad3':['Yoghurt','Granola','Frugt','Mandler'],
 'idea:morgenmad4':['Boller','Ost','Marmelade','Kakao'],
 'idea:morgenmad5':['Havregryn','Banan','Mælk'],
 'idea:morgenmad6':['Æg','Rugbrød','Juice','Grøntsager'],
 'idea:morgenmad7':['Franskbrød','Peanutbutter','Banan'],
 'idea:frokost0':['Brød til sandwich','Kylling','Ost','Grønt'],
 'idea:frokost1':['Pasta','Tun','Majs'],
 'idea:frokost2':['Rugbrød','Æg','Makrel','Grønt'],
 'idea:frokost3':['Wraps','Kylling','Avocado','Ris'],
 'idea:frokost4':['Ris','Æg','Grøntsager','Edamame'],
 'idea:frokost5':['Bagel','Laks','Flødeost','Frugt'],
 'idea:frokost6':['Pitabrød','Falafel','Hummus','Grønt'],
 'idea:frokost7':['Pasta','Pesto','Mozzarella','Tomat'],
 'idea:aftensmad0':['Ris','Kylling','Grøntsager','Sauce'],
 'idea:aftensmad1':['Pasta','Hakket kød','Tomatsauce','Parmesan'],
 'idea:aftensmad2':['Laks','Kartofler','Grønt','Dressing'],
 'idea:aftensmad3':['Ris','Hakket kød','Bønner','Tomat','Yoghurt']
};
function shoppingItems(){return (data.shoppingItems||[]).filter(item=>item.userId===data.userId);}
function renderShopping(){const list=document.getElementById('shoppingList');if(!list)return;list.innerHTML=shoppingItems().map(item=>`<div class="flow-shopping"><label class="flow-check"><input type="checkbox" data-shop-check="${esc(item.id)}" ${item.done?'checked':''}><span class="${item.done?'is-done':''}">${esc(item.text)}<small>${esc(item.meal)}</small></span></label><button type="button" class="text-button" data-shop-delete="${esc(item.id)}">${flowText('Fjern','Remove')}</button></div>`).join('')||`<p class="foot">${flowText('Vælg måltider og tilføj de ingredienser, du mangler.','Choose meals and add the ingredients you need.')}</p>`;const select=document.getElementById('shoppingMealChoice'),previous=select.value;select.innerHTML=shoppingMeals().map(m=>`<option value="${esc(m.key)}">${esc(m.name)}</option>`).join('');if(shoppingMeals().some(m=>m.key===previous))select.value=previous;}
function loadShoppingIngredients(){const f=document.getElementById('shoppingForm'),key=f.elements.meal.value;f.elements.ingredients.value=ensureLibraryProfile().shoppingRecipes?.[key]||(shoppingRecipeDefaults[key]||[]).join('\n');document.getElementById('shoppingIngredientHint').textContent=flowText('Forslag kan redigeres. Angiv mængder til dine portioner, én vare pr. linje. Egne måltider uden ingrediensliste udfyldes første gang; listen huskes bagefter. Varer fra flere måltider vises separat, så mængder ikke sammenlægges forkert.','Edit suggestions and enter quantities for your portions, one ingredient per line. Add ingredients for custom meals once; the list is remembered. Ingredients from different meals stay separate to avoid incorrect quantity totals.');}
document.addEventListener('DOMContentLoaded',()=>{
 const t=flowText,daily=document.createElement('article');daily.id='dailyPlan';daily.className='card everyday-card';document.querySelector('#home .daily-strip').after(daily);
 const week=document.createElement('article');week.id='weeklyReview';week.className='card everyday-card';document.getElementById('sevenDayAgenda').after(week);
 const copy=document.createElement('div');copy.className='flow-actions';copy.innerHTML=`<button type="button" class="button secondary" id="openCopyMeals">${t('Kopiér måltider','Copy meals')}</button><button type="button" class="text-button" id="undoCopyMeals" hidden>${t('Fortryd kopiering','Undo copy')}</button>`;document.getElementById('mealCategoryRows').before(copy);
 const copyDialog=document.createElement('dialog');copyDialog.id='copyMealsDialog';copyDialog.className='flow-dialog';copyDialog.innerHTML=`<div class="card-top"><h2>${t('Kopiér måltider','Copy meals')}</h2><button type="button" class="icon-button" data-close-flow="copyMealsDialog" aria-label="${t('Luk','Close')}">×</button></div><form id="copyMealsForm"><label class="field">${t('Kopiér fra','Copy from')}<input name="source" type="date" max="${today()}" required></label><label class="field">${t('Til dato','To date')}<input name="target" type="date" max="${today()}" required></label><div id="copyMealChoices"></div><p class="foot">${t('Kun de markerede måltider tilføjes som nye madlogs. Intet overskrives.','Only selected meals are added as new food logs. Nothing is overwritten.')}</p><p id="copyMealError" role="alert"></p><button type="submit" class="button full">${t('Kopiér valgte måltider','Copy selected meals')}</button></form>`;document.body.append(copyDialog);
 document.getElementById('openCopyMeals').onclick=()=>{const f=document.getElementById('copyMealsForm');f.elements.source.value=shiftDate(foodLogDate(),-1);f.elements.target.value=foodLogDate();document.getElementById('copyMealError').textContent='';renderCopyMeals();copyDialog.showModal();};document.querySelector('#copyMealsForm [name=source]').onchange=renderCopyMeals;
 document.getElementById('copyMealsForm').onsubmit=e=>{e.preventDefault();try{const f=e.target;copiedMealIds=copyMeals([...f.querySelectorAll('[name=meal]:checked')].map(el=>el.value),f.elements.source.value,f.elements.target.value);document.getElementById('foodLogDate').value=f.elements.target.value;save();document.getElementById('undoCopyMeals').hidden=false;copyDialog.close();toast(t('Måltider kopieret','Meals copied'));}catch(err){document.getElementById('copyMealError').textContent=err.message;}};
 document.getElementById('undoCopyMeals').onclick=()=>{data.meals=data.meals.filter(m=>!copiedMealIds.includes(m.id));copiedMealIds=[];save();document.getElementById('undoCopyMeals').hidden=true;};
 const repeat=document.createElement('button');repeat.type='button';repeat.className='button secondary full';repeat.id='openRepeatActivity';repeat.textContent=t('Gentag en aktivitet ugentligt','Repeat an activity weekly');document.getElementById('plan').prepend(repeat);
 const repeatDialog=document.createElement('dialog');repeatDialog.id='repeatActivityDialog';repeatDialog.className='flow-dialog';repeatDialog.innerHTML=`<div class="card-top"><h2>${t('Gentag aktivitet','Repeat activity')}</h2><button type="button" class="icon-button" data-close-flow="repeatActivityDialog" aria-label="${t('Luk','Close')}">×</button></div><form id="repeatActivityForm"><label class="field">${t('Aktivitet','Activity')}<select name="event" required></select></label><label class="field">${t('Antal ekstra uger','Additional weeks')}<input name="count" type="number" min="1" max="8" value="4" required></label><p id="repeatPreview" class="foot flow-preview"></p><p class="foot">${t('Du opretter separate kalenderaftaler. De kan redigeres og slettes enkeltvis. Samme program beholdes; tjek kampbelastningen for hver uge.','Creates separate events you can edit and delete individually. The same workout is retained; check match load for each week.')}</p><button class="button full" type="submit">${t('Tilføj viste datoer','Add displayed dates')}</button></form>`;document.body.append(repeatDialog);
 repeat.onclick=()=>{const f=document.getElementById('repeatActivityForm');f.elements.event.innerHTML=data.events.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<option value="${esc(e.id)}">${esc(dateText(e.date))} · ${esc(e.title||e.type)}</option>`).join('');f.querySelector('[type=submit]').disabled=!data.events.length;renderRepeatPreview();repeatDialog.showModal();};document.getElementById('repeatActivityForm').oninput=renderRepeatPreview;document.getElementById('repeatActivityForm').onsubmit=e=>{e.preventDefault();const f=e.target,event=data.events.find(x=>x.id===f.elements.event.value);if(!event)return;const rows=repetitionCandidates(event,Math.min(8,Math.max(1,Number(f.elements.count.value)||1)));data.events.push(...rows);save();repeatDialog.close();toast(rows.length+' '+t('aktiviteter tilføjet','activities added'));};
 const shop=document.createElement('details');shop.className='card everyday-card';shop.id='shoppingPanel';shop.innerHTML=`<summary>${t('Indkøbsliste','Shopping list')}</summary><div id="shoppingList"></div><details><summary>+ ${t('Tilføj fra et måltid','Add from a meal')}</summary><form id="shoppingForm"><label class="field">${t('Måltid','Meal')}<select name="meal" id="shoppingMealChoice"></select></label><label class="field">${t('Ingredienser og mængder','Ingredients and amounts')}<textarea name="ingredients" rows="5" maxlength="4000" required placeholder="250 g ris&#10;120 g kylling"></textarea></label><p id="shoppingIngredientHint" class="foot"></p><button class="button secondary full" type="submit">${t('Tilføj til indkøbslisten','Add to shopping list')}</button></form></details><button type="button" class="text-button" id="clearBought">${t('Fjern købte varer','Remove purchased items')}</button></details>`;document.getElementById('fuel').append(shop);
 document.getElementById('shoppingMealChoice').onchange=loadShoppingIngredients;document.getElementById('shoppingForm').onsubmit=e=>{e.preventDefault();const f=e.target,meal=shoppingMeals().find(m=>m.key===f.elements.meal.value),lines=f.elements.ingredients.value.split('\n').map(s=>s.trim()).filter(Boolean).slice(0,60);if(!meal||!lines.length)return;const lib=ensureLibraryProfile();lib.shoppingRecipes||={};lib.shoppingRecipes[meal.key]=lines.join('\n');data.shoppingItems||=[];lines.forEach(text=>data.shoppingItems.push({id:crypto.randomUUID(),userId:data.userId,text:text.slice(0,200),meal:meal.name,mealKey:meal.key,category:mealCategory(meal),done:false}));save();toast(t('Ingredienser tilføjet','Ingredients added'));};document.getElementById('clearBought').onclick=()=>{data.shoppingItems=(data.shoppingItems||[]).filter(i=>i.userId!==data.userId||!i.done);save();};render();loadShoppingIngredients();
});
document.addEventListener('click',e=>{
 const close=e.target.closest('[data-close-flow]');if(close)document.getElementById(close.dataset.closeFlow).close();
 const meal=e.target.closest('[data-flow-meal]');if(meal){document.getElementById('foodLogDate').value=meal.dataset.flowMeal;showTab('fuel');selectFoodView('log');render();}
 const start=e.target.closest('[data-start-planned]');if(start){const event=data.events.find(x=>x.id===start.dataset.startPlanned);if(!event)return;const record=allWorkoutRecords().find(w=>w.id===event.programId)||allWorkoutRecords().find(w=>w.name===event.title);trainingDate=event.date;workoutMode='auto';const index=workoutRecords(currentMode()).findIndex(w=>w.id===record?.id);if(index<0){showTab('train');selectProgramView('manage');toast(flowText('Programmet er ikke valgt til denne kampbelastning. Tilvælg det under Programmer.','This workout is not enabled for this match load. Enable it under Workouts.'));return;}workoutIndex=index;showTab('train');selectProgramView('train');renderWorkout();}
 const previous=e.target.closest('[data-previous-lift]');if(previous){const form=previous.previousElementSibling,last=previousLiftFor(form);if(!last)return;['sets','reps','kg'].forEach(key=>{if(last[key]!=null)form.elements[key].value=last[key];});form.dataset.dirty='true';rememberWorkoutFields();}
 const del=e.target.closest('[data-shop-delete]');if(del){data.shoppingItems=(data.shoppingItems||[]).filter(i=>!(i.id===del.dataset.shopDelete&&i.userId===data.userId));save();}
});
document.addEventListener('change',e=>{if(e.target.matches('[data-shop-check]')){const item=shoppingItems().find(i=>i.id===e.target.dataset.shopCheck);if(item){item.done=e.target.checked;save();}}});
