document.addEventListener('DOMContentLoaded',()=>{
  const recipeNote=document.createElement('p');recipeNote.className='foot';recipeNote.textContent='Opskriftsbiblioteket og danske varenavne vises på originalsproget.';document.getElementById('mealSuggestions').before(recipeNote);
  const editor=document.createElement('details');editor.id='workoutEditor';editor.className='card library-editor';
  editor.innerHTML=`<summary>Redigér pas og øvelser</summary><p class="foot">Ændringer gælder kun din lokale profil. Tidligere træningslogs ændres ikke.</p><div id="editableExercises"></div><h3>Tilføj fra bibliotek</h3><label class="field">Søg øvelse<input id="exerciseLibraryQuery" type="search" placeholder="Fx squat eller bagskulder"></label><form id="addLibraryExercise" class="form"><label class="field span">Øvelse<select name="exerciseId" id="exerciseLibraryChoice" required></select></label><label class="field">Sæt<input name="sets" type="number" min="1" max="100" value="3" required></label><label class="field">Reps / sekunder<input name="reps" maxlength="20" value="8" required></label><button class="button span">Tilføj til passet</button></form><details class="library-sub"><summary>Opret egen øvelse</summary><form id="createExercise" class="form"><label class="field span">Navn<input name="name" maxlength="100" required placeholder="Fx knæøvelse fra fysioterapeut"></label><button class="button secondary span">Gem i mit bibliotek</button></form><p class="foot">Kun i dit bibliotek. Tilføj den bagefter til et pas. En øvelse her er ikke en medicinsk anbefaling.</p></details><details class="library-sub"><summary>Opret eget pas</summary><form id="createWorkout" class="form"><label class="field span">Navn på pas<input name="name" maxlength="100" required placeholder="Fx mit personlige pas"></label><button class="button secondary span">Opret pas</button></form></details><p id="libraryStatus" role="status" class="foot"></p>`;
  document.getElementById('workoutExercises').after(editor);
  const food=document.createElement('details');food.className='card library-editor';food.id='basicFoodEditor';
  food.innerHTML=`<summary>Opret basisvare</summary><p class="foot">Gem fx Faxe Kondi eller Mathilde kakao i dit varebibliotek. Brug tallene på emballagen pr. 100 g eller 100 ml. Der logges ikke et måltid, før du selv vælger en mængde.</p><form id="basicFoodForm" class="form"><label class="field span">Varenavn<input name="name" maxlength="100" required placeholder="Fx Mathilde kakao"></label><label class="field span">Mærke (valgfrit)<input name="brand" maxlength="100"></label><label class="field">Næring pr.<select name="unit"><option value="g">100 g</option><option value="ml">100 ml</option></select></label><label class="field">Kalorier<input name="kcal" type="number" min="0" max="1000" step="0.1" required></label><label class="field">Protein (g)<input name="protein" type="number" min="0" max="100" step="0.1" required></label><button class="button span">Gem basisvare</button></form><p id="basicFoodStatus" role="status" class="foot"></p><h3>Mine basisvarer</h3><div id="myBasicFoods"></div>`;
  document.querySelector('[data-food-panel="search"]').prepend(food);
  document.getElementById('exerciseLibraryQuery').addEventListener('input',renderExerciseLibrary);
  document.getElementById('createExercise').addEventListener('submit',e=>{e.preventDefault();try{const exercise=createPrivateExercise(e.target.elements.name.value);save();e.target.reset();document.getElementById('exerciseLibraryQuery').value='';renderExerciseLibrary();document.getElementById('exerciseLibraryChoice').value=exercise.id;libraryStatus('Øvelsen er gemt. Tryk Tilføj til passet for at bruge den.');}catch(err){libraryStatus(err.message);}});
  document.getElementById('addLibraryExercise').addEventListener('submit',e=>{e.preventDefault();const f=e.target,id=f.elements.exerciseId.value;if(!availableExercises().some(x=>x.id===id))return;editWorkoutEntries(currentMode(),workoutIndex,entries=>[...entries,{id:crypto.randomUUID(),exerciseId:id,sets:f.elements.sets.value,reps:libraryName(f.elements.reps.value)}]);save();libraryStatus('Øvelsen er tilføjet til passet.');});
  document.getElementById('createWorkout').addEventListener('submit',e=>{e.preventDefault();const name=libraryName(e.target.elements.name.value);if(!name)return;if(personalPlans()[currentMode()].some(p=>p[0].toLocaleLowerCase()===name.toLocaleLowerCase())){libraryStatus('Et pas med dette navn findes allerede');return;}ensureLibraryProfile().workouts.push({id:crypto.randomUUID(),userId:data.userId,name,entries:[]});workoutIndex=workoutRecords(currentMode()).length-1;save();e.target.reset();libraryStatus('Passet er oprettet. Tilføj øvelser fra biblioteket.');});
  document.getElementById('basicFoodForm').addEventListener('submit',e=>{e.preventDefault();try{saveBasicFood(Object.fromEntries(new FormData(e.target)));save();e.target.reset();renderBasicFoods();document.getElementById('basicFoodStatus').textContent='Basisvaren er gemt. Ingen måltider er logget.';searchFood(document.querySelector('#foodSearchForm [name=query]').value||'');}catch(err){document.getElementById('basicFoodStatus').textContent=err.message;}});
  renderWorkoutEditor();renderBasicFoods();
});
function libraryStatus(text){document.getElementById('libraryStatus').textContent=text;}
function renderExerciseLibrary() {
  const select=document.getElementById('exerciseLibraryChoice');if(!select)return;
  const previous=select.value,q=document.getElementById('exerciseLibraryQuery').value.toLocaleLowerCase();
  const entries=availableExercises().filter(x=>x.name.toLocaleLowerCase().includes(q));
  select.innerHTML=['shared','private'].map(kind=>`<optgroup label="${kind==='shared'?'Fælles bibliotek':'Mine øvelser'}">${entries.filter(x=>!!x.shared===(kind==='shared')).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</optgroup>`).join('');
  if(entries.some(x=>x.id===previous))select.value=previous;
  if(!entries.length)select.innerHTML='<option value="">Ingen øvelser fundet</option>';
}
function renderWorkoutEditor() {
  const target=document.getElementById('editableExercises');if(!target)return;
  const record=workoutRecords(currentMode())[workoutIndex];
  target.innerHTML=`<h3>${esc(record.name)}</h3>`+record.entries.filter(entry=>workoutEntryRaw(entry)!==null).map(entry=>`<form class="edit-exercise-row" data-edit-entry="${esc(entry.id)}"><strong translate="no">${esc(workoutExercise(workoutEntryRaw(entry)).name)}</strong><label>Sæt<input name="sets" type="number" min="1" max="100" value="${parseInt(entry.sets,10)||3}" required></label><label>Reps / sekunder<input name="reps" maxlength="20" value="${esc(entry.reps)}" required></label><button type="submit" class="button secondary">Gem ændring</button><button type="button" class="text-button" data-delete-entry="${esc(entry.id)}">Slet fra pas</button></form>`).join('')+(record.entries.length?'':'<p class="foot">Passet er tomt. Tilføj din første øvelse nedenfor.</p>');
  renderExerciseLibrary();
}
function renderBasicFoods(){const target=document.getElementById('myBasicFoods');if(!target)return;const foods=visibleCustomFoods().filter(f=>f.source==='manual');target.innerHTML=foods.map(f=>`<div class="history-log-row"><span translate="no">${esc(f.name)}<small>${esc(f.kcal)} kcal · ${esc(f.protein)} g protein / 100 ${esc(f.unit)}</small></span><button type="button" class="text-button" data-delete-food="${esc(f.id)}">Slet</button></div>`).join('')||'<p class="foot">Ingen egne basisvarer endnu.</p>';}
const libraryWorkoutBase=renderWorkout;
renderWorkout=function(){libraryWorkoutBase();renderWorkoutEditor();renderBasicFoods();};
document.addEventListener('click',e=>{
  const deletion=e.target.closest('[data-delete-entry]');
  if(deletion){editWorkoutEntries(currentMode(),workoutIndex,entries=>entries.filter(x=>x.id!==deletion.dataset.deleteEntry));save();libraryStatus('Øvelsen er fjernet fra passet. Dine logs er bevaret.');}
  const food=e.target.closest('[data-delete-food]');if(food){data.customFoods=data.customFoods.filter(f=>!(f.id===food.dataset.deleteFood&&f.userId===data.userId&&f.source==='manual'));save();renderBasicFoods();searchFood(document.querySelector('#foodSearchForm [name=query]').value||'');}
});
document.addEventListener('submit',e=>{const form=e.target;if(!form.matches('[data-edit-entry]'))return;e.preventDefault();editWorkoutEntries(currentMode(),workoutIndex,entries=>entries.map(x=>x.id===form.dataset.editEntry?{...x,sets:form.elements.sets.value,reps:libraryName(form.elements.reps.value)}:x));save();libraryStatus('Ændringen er gemt i dit pas.');});
