const scanText=(da,en)=>{EN[da]=en;return da;};
let scanControls=null,scanGeneration=0,productRequest=null,scannedBarcode='';
function scannerStatus(da,en){document.getElementById('scannerStatus').textContent=scanText(da,en);}
function stopFoodScanner(){scanGeneration++;scanControls?.stop();scanControls=null;const video=document.getElementById('barcodeVideo');if(video){video.srcObject?.getTracks().forEach(track=>track.stop());video.srcObject=null;video.hidden=true;}document.getElementById('stopScanner')?.setAttribute('hidden','');}
function scannerAbort(){stopFoodScanner();productRequest?.abort();productRequest=null;}
function validProductBarcode(code){if(!/^\d{8}$|^\d{12,14}$/.test(code))return false;const digits=[...code].map(Number),last=digits.pop();return (10-digits.reverse().reduce((sum,d,i)=>sum+d*(i%2?1:3),0)%10)%10===last;}
async function lookupBarcode(raw){
 const code=String(raw).replace(/[\s-]/g,'');
 if(!validProductBarcode(code)){scannerStatus('Skriv en gyldig EAN/UPC-stregkode fra emballagen.','Enter a valid EAN/UPC barcode from the package.');return;}
 stopFoodScanner();productRequest?.abort();const request=new AbortController();productRequest=request;const timeout=setTimeout(()=>request.abort(),12000);
 scannedBarcode='';document.getElementById('scannedProduct').hidden=true;document.getElementById('barcodeInput').value=code;
 scannerStatus('Slår varen op i Open Food Facts…','Looking up the product in Open Food Facts…');
 try{
  const response=await fetch('https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(code)+'.json?fields=product_name,brands,nutriments',{signal:request.signal,headers:{Accept:'application/json'}});
  if(!response.ok)throw Error('network');const result=await response.json();if(productRequest!==request)return;
  if(result.status!==1||!result.product){scannerStatus('Varen blev ikke fundet. Opret den som basisvare ud fra emballagen nedenfor.','Product not found. Create it as a basic food using the package label below.');return;}
  const product=result.product,n=product.nutriments||{},form=document.getElementById('scannedProduct');
  const nutrient=value=>value!==undefined&&value!==null&&Number.isFinite(Number(value))&&Number(value)>=0?Number(value):'';
  form.reset();form.elements.name.value=product.product_name||code;
  form.elements.kcal.value=nutrient(n['energy-kcal_100g']);form.elements.protein.value=nutrient(n.proteins_100g);form.elements.unit.value='';form.elements.amount.value=100;
  scannedBarcode=code;form.hidden=false;document.getElementById('scannerSource').href='https://world.openfoodfacts.org/product/'+code;
  scannerStatus('Vare fundet. Kontrollér navn og næring på etiketten, og vælg g eller ml. Manglende tal skal udfyldes.','Product found. Check the label values and choose g or ml. Fill in any missing values.');
 }catch(error){if(productRequest===request)scannerStatus('Opslaget kunne ikke gennemføres. Tjek internetforbindelsen, eller opret varen manuelt.','Lookup failed. Check your connection or create the food manually.');}
 finally{clearTimeout(timeout);if(productRequest===request)productRequest=null;}
}
async function startFoodScanner(){
 stopFoodScanner();const generation=scanGeneration;
 if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){scannerStatus('Kamera kræver HTTPS og en understøttet browser. Brug foto eller skriv koden i stedet.','Camera access requires HTTPS and a supported browser. Use a photo or enter the code instead.');return;}
 const video=document.getElementById('barcodeVideo');video.hidden=false;document.getElementById('stopScanner').hidden=false;
 scannerStatus('Hold stregkoden roligt foran kameraet.','Hold the barcode steady in front of the camera.');
 try{const reader=new ZXingBrowser.BrowserMultiFormatReader();let found=false;const controls=await reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'}},audio:false},video,(result,error,controls)=>{if(generation!==scanGeneration){controls?.stop();return;}if(result&&!found&&validProductBarcode(result.getText())){found=true;controls.stop();lookupBarcode(result.getText());}});if(generation!==scanGeneration)controls.stop();else scanControls=controls;}
 catch(error){if(generation===scanGeneration){stopFoodScanner();scannerStatus('Kunne ikke åbne kameraet. Tillad kamera i browseren, eller brug foto/kode.','Could not open the camera. Allow camera access or use a photo/code.');}}
}
document.addEventListener('DOMContentLoaded',()=>{
 const card=document.createElement('details');card.className='card scanner-card';card.id='foodScanner';card.innerHTML=`<summary>${scanText('Scan madvare','Scan food barcode')}</summary><p class="foot">${scanText('Scan en stregkode på emballagen. Billeder behandles på enheden; kun stregkoden sendes til Open Food Facts. Vareopslag kræver internet.','Scan a barcode on the package. Images are processed on your device; only the barcode is sent to Open Food Facts. Product lookup requires internet.')}</p><div class="toolbar"><button type="button" class="button secondary" id="startScanner">${scanText('Åbn kamera','Open camera')}</button><button type="button" class="text-button" id="stopScanner" hidden>${scanText('Stop kamera','Stop camera')}</button></div><video id="barcodeVideo" muted playsinline hidden></video><label class="field">${scanText('Eller vælg et foto af stregkoden','Or choose a barcode photo')}<input id="barcodePhoto" type="file" accept="image/*" capture="environment"></label><form id="barcodeForm" class="form"><label class="field span">${scanText('Stregkode','Barcode')}<input id="barcodeInput" inputmode="numeric" pattern="[0-9 -]{8,20}" maxlength="20" required autocomplete="off"></label><button class="button secondary span">${scanText('Find vare','Find product')}</button></form><p id="scannerStatus" class="foot" role="status"></p><form id="scannedProduct" class="scanner-fields" hidden><label class="field span">${scanText('Varenavn','Product name')}<input name="name" required maxlength="150"></label><label class="field">kcal / 100 g/ml<input name="kcal" type="number" min="0" max="1000" step="any" required></label><label class="field">Protein / 100 g/ml<input name="protein" type="number" min="0" max="100" step="any" required></label><label class="field">${scanText('Enhed på etiketten','Label unit')}<select name="unit" required><option value="">${scanText('Vælg g eller ml','Choose g or ml')}</option><option value="g">g</option><option value="ml">ml</option></select></label><label class="field">${scanText('Mængde spist/drukket','Amount eaten/drunk')}<input name="amount" type="number" min="0.1" max="10000" step="any" required></label><label class="span"><input type="checkbox" name="keep"> ${scanText('Gem også som min basisvare','Also save as my basic food')}</label><a class="foot span" id="scannerSource" target="_blank" rel="noopener">Open Food Facts · ${scanText('kontrollér kilden','check source')}</a><button class="button span">${scanText('Log på valgt maddato','Log on selected food date')}</button></form>`;
 document.querySelector('[data-food-panel="search"]').prepend(card);
 card.addEventListener('toggle',()=>{if(!card.open)scannerAbort();});
 document.getElementById('startScanner').addEventListener('click',startFoodScanner);document.getElementById('stopScanner').addEventListener('click',()=>{stopFoodScanner();scannerStatus('Kamera stoppet.','Camera stopped.');});
 document.getElementById('barcodeForm').addEventListener('submit',e=>{e.preventDefault();lookupBarcode(document.getElementById('barcodeInput').value);});
 document.getElementById('barcodePhoto').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;stopFoodScanner();const generation=scanGeneration,url=URL.createObjectURL(file);try{scannerStatus('Læser stregkode fra foto…','Reading barcode from photo…');const result=await new ZXingBrowser.BrowserMultiFormatReader().decodeFromImageUrl(url);if(generation===scanGeneration)await lookupBarcode(result.getText());}catch{if(generation===scanGeneration)scannerStatus('Stregkoden kunne ikke læses. Prøv et skarpere foto eller skriv koden.','Could not read the barcode. Try a sharper photo or enter the code.');}finally{URL.revokeObjectURL(url);e.target.value='';}});
 document.getElementById('scannedProduct').addEventListener('submit',e=>{e.preventDefault();const form=e.target;if(!scannedBarcode||!form.reportValidity())return;const values=Object.fromEntries(new FormData(form)),amount=Number(values.amount),kcal=Number(values.kcal),protein=Number(values.protein);if(!Number.isFinite(amount)||amount<=0||!Number.isFinite(kcal)||kcal<0||!Number.isFinite(protein)||protein<0)return;const oldMeals=[...data.meals],oldFoods=[...data.customFoods];try{if(values.keep){const item=saveBasicFood(values);item.barcode=scannedBarcode;}data.meals.push({id:crypto.randomUUID(),date:foodLogDate(),name:values.name+' · '+amount+' '+values.unit,kcal:Math.round(kcal*amount/100),protein:Math.round(protein*amount/100*10)/10,barcode:scannedBarcode});save();form.hidden=true;scannedBarcode='';scannerStatus('Måltidet er gemt på den valgte dato.','Meal saved on the selected date.');}catch{data.meals=oldMeals;data.customFoods=oldFoods;scannerStatus('Kunne ikke gemme. Prøv igen.','Could not save. Please try again.');}});
});
document.addEventListener('visibilitychange',()=>{if(document.hidden)scannerAbort();});window.addEventListener('pagehide',scannerAbort);
document.addEventListener('click',e=>{if(e.target.closest('[data-tab],[data-action="tab"],[data-food-view]'))scannerAbort();});
