const smoothText=(da,en)=>appLanguage()==='en'?en:da;
Object.assign(EN,{'Træn':'Train','Programmer':'Workouts','Forrige 7 dage':'Previous 7 days','Næste 7 dage':'Next 7 days','Ingen pas valgt til denne uge. Vælg eller opret et program ovenfor.':'No workouts selected for this week. Choose or create a workout above.'});
let programView='train',programFilter='all',smoothRangeStart=today();
function selectProgramView(view){programView=view;document.querySelectorAll('[data-program-panel]').forEach(el=>el.hidden=el.dataset.programPanel!==view);document.querySelectorAll('[data-program-view]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.programView===view)));renderProgramManager();}
function renderProgramManager(){const target=document.getElementById('programCards');if(!target)return;const lib=ensureLibraryProfile(),all=allWorkoutRecords(),archived=lib.archivedPrograms||[];
 [0,1,2].forEach(mode=>{document.querySelector(`#gameCount option[value="${mode}"]`).textContent=`${mode===2?'2+':mode} ${smoothText('kampe','matches')} · ${workoutRecords(mode).length} ${smoothText('pas','workouts')}`;});
 document.getElementById('planHint').textContent=smoothText('Vælg pas til den valgte uge. Tilpas kampuger under Programmer.','Choose a workout for the selected week. Set match weeks under Workouts.');
 target.innerHTML=all.filter(w=>!archived.includes(w.id)&&(programFilter==='all'||programAssigned(w.id,Number(programFilter)))).map(w=>`<article class="program-row"><div class="program-row-title"><button type="button" data-open-program="${esc(w.id)}"><strong translate="no">${esc(w.name)}</strong><small>${w.entries.length} ${smoothText('øvelser','exercises')} · ${w.shared?smoothText('Tilpasset standardpas','Customisable template'):smoothText('Dit eget pas','Your own workout')}</small></button><button type="button" class="remove-program" data-archive-program="${esc(w.id)}" aria-label="${smoothText('Fjern','Remove')} ${esc(w.name)}">${smoothText('Fjern','Remove')}</button></div><span class="program-when">${smoothText('Brug i uger med','Use in weeks with')}</span><div class="program-modes">${[0,1,2].map(mode=>`<button type="button" data-assign-program="${esc(w.id)}" data-mode="${mode}" aria-pressed="${programAssigned(w.id,mode)}">${mode===2?'2+':mode} ${smoothText('kampe','matches')}</button>`).join('')}</div></article>`).join('')||`<p class="foot">${smoothText('Ingen programmer her. Opret et nyt, eller tilvælg et fra Alle.','No workouts here. Create one or enable one under All.')}</p>`;
 document.getElementById('archivedPrograms').innerHTML=archived.length?`<details><summary>${smoothText('Fjernede programmer','Removed workouts')} (${archived.length})</summary>${all.filter(w=>archived.includes(w.id)).map(w=>`<div class="history-log-row"><span translate="no">${esc(w.name)}</span><button type="button" class="text-button" data-restore-program="${esc(w.id)}">${smoothText('Gendan','Restore')}</button></div>`).join('')}</details>`:'';
}
function openManagedProgram(id){let mode=currentMode();if(!programAssigned(id,mode)){assignProgram(id,mode,true);save();}workoutIndex=workoutRecords(mode).findIndex(w=>w.id===id);renderWorkout();selectProgramView('train');document.getElementById('workoutEditor').open=true;document.getElementById('workoutEditor').scrollIntoView({block:'start',behavior:'smooth'});}
const smoothWorkoutBase=renderWorkout;
renderWorkout=function(){smoothWorkoutBase();document.querySelectorAll('.exercise-entry').forEach((row,i)=>{const id=workoutEntryId(currentMode(),workoutIndex,i),button=document.createElement('button');button.type='button';button.className='exercise-remove';button.dataset.deleteEntry=id;button.textContent=smoothText('Fjern','Remove');button.setAttribute('aria-label',smoothText('Fjern øvelse fra dette pas','Remove exercise from this workout'));row.firstElementChild.append(button);});const disabled=!workoutRecords(currentMode()).length;document.querySelector('#addLibraryExercise button')?.toggleAttribute('disabled',disabled);renderProgramManager();};
const smoothDashboardBase=renderDashboard;
renderDashboard=function(){smoothDashboardBase();if(overviewDate<smoothRangeStart||overviewDate>shiftDate(smoothRangeStart,6))smoothRangeStart=overviewDate;
 const dates=Array.from({length:7},(_,i)=>shiftDate(smoothRangeStart,i));document.getElementById('dashboardWeek').innerHTML=dates.map(date=>{const count=dayCountLabel(date);return `<button type="button" class="smooth-day ${date===overviewDate?'selected':''} ${count.logs||count.planned?'populated':''}" data-history-date="${date}" aria-pressed="${date===overviewDate}" aria-label="${esc(historyLabel(date))}: ${count.logs} logs, ${count.planned} ${smoothText('planlagte','planned')}"><span>${new Date(date+'T12:00:00').toLocaleDateString(appLocale(),{weekday:'short'}).replace('.','')}</span><strong>${Number(date.slice(-2))}</strong><small>${count.logs||count.planned?count.logs+count.planned:'—'}</small></button>`;}).join('');
 const meals=data.meals.filter(m=>m.date===overviewDate),kcal=meals.reduce((s,m)=>s+Number(m.kcal||0),0),protein=meals.reduce((s,m)=>s+Number(m.protein||0),0),goal=overviewDate>=today()?Number(currentKcalGoal(overviewDate))||0:0,percent=goal?Math.min(100,kcal/goal*100):0;
 document.getElementById('dashboardStats').innerHTML=`<button type="button" class="energy-summary" data-history-open><div><span class="eyebrow">${smoothText('DIN ENERGI','YOUR ENERGY')}</span><strong>${meals.length?uiNumber(kcal):'—'}<small> kcal</small></strong><span>${smoothText('Registreret','Recorded')} · ${esc(historyLabel(overviewDate).toLowerCase())}</span><p>${goal?uiNumber(Math.max(0,goal-kcal))+' kcal '+smoothText('tilbage af','remaining of')+' '+uiNumber(goal):smoothText('Se kalorier og vægt over tid','View calories and weight over time')}</p></div><div class="energy-ring" style="--progress:${percent}%"><span>${goal?Math.round(percent)+'%':'↗'}<small>${smoothText('Udvikling','Progress')}</small></span></div><div class="energy-protein"><span>${smoothText('Protein','Protein')}</span><strong>${meals.length?uiNumber(protein):'—'} g</strong></div></button>`;
 const agenda=document.getElementById('sevenDayAgenda');if(agenda){const end=shiftDate(today(),6);agenda.innerHTML=`<div class="card-top"><h2>${smoothText('De næste 7 dage','The next 7 days')}</h2><button type="button" class="text-button" data-action="tab" data-value="plan">${smoothText('Kalender','Calendar')} ↗</button></div>`+Array.from({length:7},(_,i)=>{const date=shiftDate(today(),i),events=data.events.filter(e=>e.date===date).sort((a,b)=>String(a.time).localeCompare(String(b.time)));return `<button type="button" class="agenda-day" data-history-date="${date}"><span class="agenda-date"><small>${new Date(date+'T12:00:00').toLocaleDateString(appLocale(),{weekday:'short'})}</small><strong>${Number(date.slice(-2))}</strong></span><span><strong>${events.length?events.map(e=>esc(e.title||e.type)).join(' · '):smoothText('Ingen planlagt træning','No training scheduled')}</strong><small>${events.length?events.map(e=>esc(activityTimeLabel(e))).join(' · '):smoothText('Plads i kalenderen','Calendar is open')}</small></span><span>›</span></button>`;}).join('');}
 if(document.getElementById('smoothRangeLabel'))document.getElementById('smoothRangeLabel').textContent=dateText(dates[0])+' – '+dateText(dates[6]);
 renderMealCategories();
};
function renderMealCategories(){const target=document.getElementById('mealCategoryRows');if(!target)return;const date=foodLogDate();target.innerHTML=PRESET_CATEGORIES.map(([key,label,emoji])=>{const entries=data.meals.filter(m=>m.date===date&&m.category===key),sum=entries.reduce((n,m)=>n+Number(m.kcal||0),0);return `<button type="button" class="meal-category-row" data-log-category="${esc(key)}"><span class="meal-category-icon">${emoji}</span><span><strong>${esc(label)}</strong><small>${entries.length?uiNumber(sum)+' kcal':smoothText('Tilføj måltid','Add meal')}</small></span><span class="meal-category-plus">+</span></button>`;}).join('');}
document.addEventListener('DOMContentLoaded',()=>{
 const train=document.getElementById('train'),children=[...train.children];children.forEach(el=>el.dataset.programPanel='train');
 const nav=document.createElement('nav');nav.className='food-navigation program-navigation';nav.innerHTML='<button type="button" data-program-view="train" aria-pressed="true">Træn</button><button type="button" data-program-view="manage" aria-pressed="false">Programmer</button>';train.prepend(nav);
 const manager=document.createElement('div');manager.dataset.programPanel='manage';manager.hidden=true;manager.innerHTML=`<article class="card new-program-card"><h2>${smoothText('Opret styrkeprogram','Create strength workout')}</h2><form id="newProgramForm"><label class="field">${smoothText('Navn på program','Workout name')}<input name="name" required maxlength="100" placeholder="Upper A, full body…"></label><fieldset><legend>${smoothText('Jeg bruger det ved','I use it with')}</legend>${[0,1,2].map(m=>`<label><input type="checkbox" name="mode" value="${m}" ${m===currentMode()?'checked':''}> ${m===2?'2+':m} ${smoothText('kampe','matches')}</label>`).join('')}</fieldset><button class="button full" type="submit">+ ${smoothText('Opret program','Create workout')}</button><p id="newProgramError" role="alert" class="foot"></p></form></article><div class="program-filter"><label>${smoothText('Vis programmer','Show workouts')}<select id="programFilter"><option value="all">${smoothText('Alle','All')}</option><option value="0">0 ${smoothText('kampe','matches')}</option><option value="1">1 ${smoothText('kamp','match')}</option><option value="2">2+ ${smoothText('kampe','matches')}</option></select></label></div><div id="programCards"></div><div id="archivedPrograms"></div><p class="foot">${smoothText('Fjernelse påvirker ikke dine træningslogs. Programmer og valg gemmes på din lokale profil.','Removal does not affect your training logs. Workouts and choices are saved on your local profile.')}</p>`;train.append(manager);
 const manageButton=document.createElement('button');manageButton.type='button';manageButton.className='button secondary full manage-programs';manageButton.dataset.programView='manage';manageButton.textContent=smoothText('+ Tilføj / fjern programmer','+ Add / remove workouts');document.getElementById('workoutChoice').closest('.form').after(manageButton);
 const oldCreate=document.getElementById('createWorkout').closest('details');oldCreate.hidden=true;
 const quickAdd=document.createElement('button');quickAdd.type='button';quickAdd.className='button secondary full';quickAdd.id='quickAddExercise';quickAdd.textContent=smoothText('+ Tilføj øvelse','+ Add exercise');document.getElementById('workoutExercises').after(quickAdd);
 quickAdd.addEventListener('click',()=>{document.getElementById('workoutEditor').open=true;document.getElementById('exerciseLibraryQuery').scrollIntoView({block:'center',behavior:'smooth'});document.getElementById('exerciseLibraryQuery').focus({preventScroll:true});});
 document.getElementById('programFilter').addEventListener('change',e=>{programFilter=e.target.value;renderProgramManager();});
 document.getElementById('newProgramForm').addEventListener('submit',e=>{e.preventDefault();const form=e.target,name=libraryName(form.elements.name.value),modes=[...form.querySelectorAll('[name=mode]:checked')].map(x=>Number(x.value)),error=document.getElementById('newProgramError');if(!name||!modes.length){error.textContent=smoothText('Angiv navn og vælg mindst én kampuge.','Enter a name and choose at least one match week.');return;}if(allWorkoutRecords().some(w=>w.name.toLowerCase()===name.toLowerCase())){error.textContent=smoothText('Navnet findes allerede. Vælg et andet.','This name already exists. Choose another.');return;}const lib=ensureLibraryProfile();lib.weekPrograms ||= {};[0,1,2].forEach(m=>{lib.weekPrograms[m]=workoutRecords(m).map(w=>w.id);});const record={id:crypto.randomUUID(),userId:data.userId,name,entries:[]};lib.workouts.push(record);modes.forEach(m=>assignProgram(record.id,m,true));workoutMode=String(modes[0]);workoutIndex=workoutRecords(modes[0]).findIndex(w=>w.id===record.id);save();form.reset();form.querySelector('[name=mode]').checked=true;error.textContent='';openManagedProgram(record.id);});
 const agenda=document.createElement('article');agenda.className='card seven-day-agenda';agenda.id='sevenDayAgenda';document.getElementById('dashboardStats').after(agenda);
 const range=document.createElement('div');range.className='smooth-range';range.innerHTML='<button type="button" data-range-step="-7" aria-label="Forrige 7 dage">‹</button><span id="smoothRangeLabel"></span><button type="button" data-range-step="7" aria-label="Næste 7 dage">›</button>';document.querySelector('.daily-strip').prepend(range);
 const categories=document.createElement('div');categories.id='mealCategoryRows';categories.className='card meal-category-list';document.querySelector('[data-food-panel="log"]').prepend(categories);
 document.getElementById('foodLogDate').addEventListener('change',renderMealCategories);
 render();renderWorkout();
});
document.addEventListener('click',e=>{
 const view=e.target.closest('[data-program-view]');if(view)selectProgramView(view.dataset.programView);
 const assignment=e.target.closest('[data-assign-program]');if(assignment){const id=assignment.dataset.assignProgram,mode=Number(assignment.dataset.mode);assignProgram(id,mode,!programAssigned(id,mode));workoutIndex=0;save();}
 const remove=e.target.closest('[data-archive-program]');if(remove){archiveProgram(remove.dataset.archiveProgram);workoutIndex=0;save();}
 const restore=e.target.closest('[data-restore-program]');if(restore){restoreProgram(restore.dataset.restoreProgram);save();}
 const open=e.target.closest('[data-open-program]');if(open)openManagedProgram(open.dataset.openProgram);
 const step=e.target.closest('[data-range-step]');if(step){smoothRangeStart=shiftDate(smoothRangeStart,Number(step.dataset.rangeStep));selectOverviewDate(smoothRangeStart);}
 const meal=e.target.closest('[data-log-category]');if(meal){document.getElementById('mealForm').elements.category.value=meal.dataset.logCategory;document.getElementById('mealForm').scrollIntoView({block:'center',behavior:'smooth'});document.getElementById('mealForm').elements.name.focus({preventScroll:true});}
});
