const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:390,height:844},locale:'da-DK'}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173/app.html');
 await page.evaluate(()=>{
  const date=d=>{const x=new Date();x.setDate(x.getDate()+d);return [x.getFullYear(),String(x.getMonth()+1).padStart(2,'0'),String(x.getDate()).padStart(2,'0')].join('-')};
  localStorage.setItem('puls-mvp-v1',JSON.stringify({profile:{kcalGoal:2400,proteinGoal:120},onboarding:{completed:true},meals:[{id:'m1',date:date(-1),name:'Historisk morgenmad',kcal:650,protein:30},{id:'m2',date:date(-1),name:'Historisk frokost',kcal:850,protein:45}],events:[{id:'e1',date:date(-1),title:'Fodbold',type:'Sportstræning',time:'18:00',endTime:'19:30'}],lifts:[{id:'l1',date:date(-1),exercise:'Squat',sets:3,reps:8,kg:60}],progress:[{id:'w1',date:date(-5),type:'Vægt (kg)',value:80},{id:'w2',date:date(-1),type:'Vægt (kg)',value:81}],recovery:{[date(-1)]:{sleep:8,energy:7,soreness:3,general:3}}}));
 });await page.reload();
 await page.locator('[data-history-shift="-1"]').click();
 assert.equal(await page.locator('#pageTitle').textContent(),'I går');
 assert.match(await page.locator('#dashboardStats').textContent(),/1.500/);
 assert.match(await page.locator('#recentActivity').textContent(),/Historisk morgenmad/);
 assert.match(await page.locator('#recentActivity').textContent(),/Squat/);
 assert.match(await page.locator('#next').textContent(),/planlagt/);
 assert.equal(await page.locator('.workout-card').isVisible(),false);
 await page.screenshot({path:'/tmp/harpex-history-overview.png',fullPage:true});
 await page.locator('.history-calories').click();
 assert.equal(await page.locator('#progress').isVisible(),true);
 assert.equal(await page.locator('.history-chart').count(),2);
 assert.ok((await page.locator('.history-chart').first().boundingBox()).height>120);
 assert.match(await page.locator('#historyContent').textContent(),/\+1 kg/);
 for(const value of ['1','14','month','year','since']){await page.locator('#historyPeriod').selectOption(value);assert.ok(await page.locator('#historyContent').textContent());}
 await page.locator('#historyPeriod').selectOption('custom');
 await page.locator('#historyCustom [name=from]').fill('2026-01-01');await page.locator('#historyCustom [name=to]').fill('2026-01-15');await page.locator('#historyCustom button').click();
 assert.match(await page.locator('#historyContent').textContent(),/Ingen måltider/);
 await page.locator('#historyCustom [name=from]').fill('2026-02-01');await page.locator('#historyCustom button').click();assert.match(await page.locator('#historyError').textContent(),/fra skal være før/);
 await page.locator('#historyPeriod').selectOption('7');
 await page.locator('#trackingStart').fill('2026-01-01');await page.locator('#trackingStart').dispatchEvent('change');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('puls-mvp-v1')).trackingStart),'2026-01-01');
 await page.screenshot({path:'/tmp/harpex-history-graph.png',fullPage:true});
 await page.locator('#progressForm [name=date]').fill('2026-09-20');await page.locator('#progressForm [name=value]').fill('79.5');await page.locator('#progressForm button').click();
 assert.ok(await page.evaluate(()=>JSON.parse(localStorage.getItem('puls-mvp-v1')).progress.some(x=>x.date==='2026-09-20'&&x.value==='79.5')));
 await page.locator('.tab[data-tab=plan]').click();await page.locator('.month-day:not(.other)').first().click();assert.equal(await page.locator('#home').isVisible(),true);assert.notEqual(await page.locator('#pageTitle').textContent(),'I dag');
 await page.locator('[data-history-today]').click();assert.equal(await page.locator('#pageTitle').textContent(),'I dag');assert.equal(await page.locator('.workout-card').isVisible(),true);
 await page.reload();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('puls-mvp-v1')).trackingStart),'2026-01-01');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
 await page.locator('.quick-track[data-value=train]').click();
 await page.locator('#gameCount').selectOption('0');
 const forms=page.locator('.exerciseForm');
 await forms.nth(0).locator('[name=kg]').fill('60');
 await forms.nth(1).locator('[name=kg]').fill('42.5');
 await forms.nth(1).locator('[name=sets]').fill('5');
 await forms.nth(1).locator('[name=reps]').fill('9');
 await forms.nth(2).locator('[name=kg]').fill('32');
 const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('puls-mvp-v1')).lifts.length);
 await forms.nth(0).locator('button').click();
 assert.equal(await forms.nth(0).locator('[name=kg]').inputValue(),'');
 assert.equal(await forms.nth(1).locator('[name=kg]').inputValue(),'42.5');
 assert.equal(await forms.nth(1).locator('[name=sets]').inputValue(),'5');
 assert.equal(await forms.nth(1).locator('[name=reps]').inputValue(),'9');
 assert.equal(await forms.nth(2).locator('[name=kg]').inputValue(),'32');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('puls-mvp-v1')).lifts.length),before+1);
 await page.locator('#workoutChoice').selectOption('1');
 assert.equal(await forms.nth(1).locator('[name=kg]').inputValue(),'');
 await page.locator('#workoutChoice').selectOption('0');
 assert.equal(await forms.nth(1).locator('[name=kg]').inputValue(),'42.5');
 const originalDate=await page.locator('#trainingDate').inputValue();
 await page.locator('#trainingDate').fill('2026-09-10');await page.locator('#trainingDate').dispatchEvent('change');
 assert.equal(await forms.nth(1).locator('[name=kg]').inputValue(),'');
 await page.locator('#trainingDate').fill(originalDate);await page.locator('#trainingDate').dispatchEvent('change');
 assert.equal(await forms.nth(1).locator('[name=kg]').inputValue(),'42.5');
 await forms.nth(1).locator('button').click();
 assert.equal(await forms.nth(1).locator('[name=kg]').inputValue(),'');
 assert.equal(await forms.nth(2).locator('[name=kg]').inputValue(),'32');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('puls-mvp-v1')).lifts.length),before+2);
 await page.locator('.tab[data-tab=progress]').click();
 await page.locator('[data-ui=theme]').click();
 await page.screenshot({path:'/tmp/harpex-history-light.png',fullPage:true});
 await page.locator('[data-ui=more]').click();await page.locator('#moreMenu [data-value=profile]').click();
 const ef=page.locator('#energyForm');
 for(const [name,value] of Object.entries({age:'25',weight:'80',height:'180',sportSessions:'4',strengthSessions:'3',matchSessions:'1'}))await ef.locator(`[name=${name}]`).fill(value);
 await ef.locator('[name=sex]').selectOption('male');await ef.locator('[name=energyGoal]').selectOption('gain');await ef.locator('[name=season]').selectOption('in');await ef.locator('[type=submit]').click();
 const estimate=await page.evaluate(()=>estimateEnergy());
 assert.equal(estimate.components.surplus,400);assert.equal(estimate.components.hall,450);assert.equal(estimate.components.matches,600/7);assert.equal(estimate.today,estimate.average);
 await page.locator('#applyEnergy').click();
 assert.equal(await page.evaluate(()=>currentKcalGoal()),estimate.average);
 await ef.locator('[name=season]').selectOption('off');await ef.locator('[type=submit]').click();
 assert.equal(await page.evaluate(()=>estimateEnergy().components.hall),0);assert.equal(await page.evaluate(()=>estimateEnergy().components.surplus),400);
 await page.reload();assert.equal(await page.evaluate(()=>data.energy.season),'off');
 await page.evaluate(()=>showTab('profile'));
 assert.equal(await ef.locator('[name=season]').inputValue(),'off');
 await page.locator('[data-ui=onboard]').click();
 await page.evaluate(()=>{onboardingStep=6;renderOnboarding();});
 assert.equal(await page.locator('#onboardingForm [name=season]').inputValue(),'off');
 await page.locator('#onboardingForm [name=season]').selectOption('in');
 assert.equal(await page.evaluate(()=>onboardingDraft.season),'in');
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: history, exercise drafts, themes, season UI, estimate application, persistence, onboarding, no runtime errors');
})().catch(e=>{console.error(e);process.exit(1)});
