const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:390,height:844},locale:'da-DK'}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173/app.html');await page.evaluate(()=>{closeOnboarding(true);showTab('train');});
 await page.locator('#gameCount').selectOption('0');await page.locator('#workoutEditor>summary').click();
 const originalCount=await page.locator('.exerciseForm').count();
 await page.locator('.exerciseForm').nth(1).locator('[name=kg]').fill('42.5');
 await page.locator('[data-delete-entry]').first().click();assert.equal(await page.locator('.exerciseForm').count(),originalCount-1);
 assert.equal(await page.locator('.exerciseForm').first().locator('[name=kg]').inputValue(),'42.5','draft follows stable entry after another row is removed');
 await page.locator('#createExercise').locator('xpath=..').locator('summary').click();
 await page.locator('#createExercise [name=name]').fill('Mit knæ · test');await page.locator('#createExercise button').click();
 await page.locator('#addLibraryExercise button').click();assert.equal(await page.locator('.exerciseForm').count(),originalCount);
 assert.match(await page.locator('#workoutExercises').textContent(),/Mit knæ/);
 const customId=await page.evaluate(()=>ensureLibraryProfile().exercises[0].id),user=await page.evaluate(()=>data.userId);
 assert.equal(await page.evaluate(()=>data.meals.length),0);
 const edit=page.locator('[data-edit-entry]').last();await edit.locator('[name=sets]').fill('4');await edit.locator('[name=reps]').fill('12');await edit.locator('[type=submit]').click();
 assert.equal(await page.locator('.exerciseForm').last().locator('[name=sets]').inputValue(),'4');
 await page.locator('#createWorkout').locator('xpath=..').locator('summary').click();await page.locator('#createWorkout [name=name]').fill('Mit eget pas');await page.locator('#createWorkout button').click();
 assert.equal(await page.locator('.exerciseForm').count(),0);
 await page.locator('#exerciseLibraryChoice').selectOption(customId);await page.locator('#addLibraryExercise button').click();assert.equal(await page.locator('.exerciseForm').count(),1);
 await page.locator('.exerciseForm [name=kg]').fill('12');await page.locator('.exerciseForm button').click();
 assert.equal(await page.evaluate(()=>data.lifts.at(-1).workout),'Mit eget pas');
 await page.reload();await page.evaluate(()=>showTab('train'));assert.ok(await page.locator('#workoutChoice option').filter({hasText:'Mit eget pas'}).count());
 await page.evaluate(()=>showTab('fuel'));await page.locator('[data-food-view=search]').click();await page.locator('#basicFoodEditor>summary').click();
 for(const [name,value]of Object.entries({name:'Faxe Kondi test',brand:'Test',kcal:'40',protein:'0'}))await page.locator(`#basicFoodForm [name=${name}]`).fill(value);
 await page.locator('#basicFoodForm [name=unit]').selectOption('ml');await page.locator('#basicFoodForm button').click();
 assert.equal(await page.evaluate(()=>data.meals.length),0);assert.equal(await page.evaluate(()=>data.presets.length),0);
 await page.locator('#foodSearchForm [name=query]').fill('Faxe Kondi test');await page.locator('#foodSearchForm button').click();await page.locator('#foodResults [data-action=product]').click();
 await page.locator('#productAmount [name=amount]').fill('500');await page.locator('#productAmount button').click();
 assert.equal(await page.evaluate(()=>data.meals.at(-1).kcal),200);
 await page.locator('#foodCsv').setInputFiles({name:'foods.csv',mimeType:'text/csv',buffer:Buffer.from('navn;kcal;protein\nCSV vare;100;5')});
 await page.waitForFunction(()=>data.customFoods.some(x=>x.name==='CSV vare'));
 assert.equal(await page.evaluate(()=>data.customFoods.some(f=>f.name==='Faxe Kondi test'&&f.source==='manual')),true);
 const exported=await page.evaluate(()=>JSON.parse(JSON.stringify(data)));
 assert.ok(exported.trainingLibraries[user].workouts.some(w=>w.name==='Mit eget pas'));
 assert.equal(await page.evaluate(()=>JSON.stringify(STRENGTH_PLANS[0][0][1]).includes('Mit knæ')),false);
 await page.evaluate(()=>{data.userId='other-user';ensureLibraryProfile();render();});
 assert.equal(await page.evaluate(id=>availableExercises().some(e=>e.id===id),customId),false);
 assert.equal(await page.evaluate(()=>visibleCustomFoods().some(f=>f.name==='Faxe Kondi test')),false);
 assert.equal(await page.evaluate(()=>personalPlans()[0].some(p=>p[0]==='Mit eget pas')),false);
 assert.equal(await page.evaluate(()=>personalPlans()[0][0][1].length),originalCount);
 await page.evaluate(id=>{data.userId=id;save();showTab('profile');},user);
 await page.locator('#appLanguage').selectOption('en');await page.waitForFunction(()=>document.documentElement.lang==='en');
 assert.equal(await page.locator('.tab[data-tab=progress]').textContent(),'Progress');
 await page.evaluate(()=>showTab('train'));await page.locator('#workoutEditor').evaluate(el=>el.open=true);
 assert.equal(await page.locator('#workoutEditor>summary').textContent(),'Edit workout and exercises');
 assert.equal(await page.locator('#gameCount option[value="0"]').textContent(),'0 matches · 4 workouts');
 assert.equal(await page.locator('#gameCount').inputValue(),'auto');
 await page.locator('#gameCount').selectOption('0');assert.equal(await page.locator('#gameCount').inputValue(),'0');
 await page.screenshot({path:'/tmp/harpex-library-en.png',fullPage:true});
 await page.evaluate(()=>showTab('profile'));await page.locator('#appLanguage').selectOption('da');assert.equal(await page.locator('.tab[data-tab=progress]').textContent(),'Udvikling');
 const en=await browser.newContext({locale:'de-DE',viewport:{width:390,height:844}}),ep=await en.newPage();await ep.goto('http://127.0.0.1:4173/app.html');await ep.waitForFunction(()=>document.documentElement.lang==='en');
 assert.equal(await ep.locator('.tab[data-tab=home]').textContent(),'Overview');
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: private libraries, stable drafts, custom workouts, edit/remove persistence, basic-food amounts, owner isolation, EN/DA switching and device fallback');
})().catch(e=>{console.error(e);process.exit(1)});
