/* Original, code-native artwork. No generated photos or external assets. */
const HARPEX_ART = {
  training: '<svg viewBox="0 0 180 140" fill="none" aria-hidden="true"><path d="M-20 126C24 25 93 186 203 8M-24 109C28 9 93 168 194-10" stroke="#b9dbc7" stroke-width="2" opacity=".45"/><g transform="rotate(-28 90 70)"><rect x="43" y="61" width="96" height="17" rx="6" fill="#dbe5d8"/><rect x="30" y="43" width="22" height="54" rx="6" fill="#142c24"/><rect x="20" y="52" width="13" height="36" rx="4" fill="#9ec7b0"/><rect x="128" y="43" width="22" height="54" rx="6" fill="#142c24"/><rect x="150" y="52" width="13" height="36" rx="4" fill="#9ec7b0"/><path d="M57 65h65" stroke="#fff" stroke-opacity=".6" stroke-width="3"/></g></svg>',
  food: '<svg viewBox="0 0 180 140" fill="none" aria-hidden="true"><ellipse cx="90" cy="78" rx="59" ry="49" fill="#9c5045" opacity=".4"/><circle cx="88" cy="66" r="52" fill="#f8e8d5"/><circle cx="88" cy="66" r="43" fill="#dfc7a6"/><path d="M52 53c5-23 40-34 45-7-6 19-41 34-45 7Z" fill="#315a36"/><path d="m62 43 25 24m-18-35 17 23" stroke="#94b37a" stroke-width="3"/><path d="M96 40c30-11 44 27 14 36-17 3-30-20-14-36Z" fill="#b7c58d"/><path d="M105 44c17-4 25 16 10 23-9 3-18-14-10-23Z" fill="#e4dfad"/><circle cx="111" cy="55" r="8" fill="#946443"/><path d="m60 81 23-10 14 19-24 9Z" fill="#c28849"/><path d="m67 79 13 17m-4-21 13 18" stroke="#855c37" stroke-width="3"/><circle cx="110" cy="88" r="8" fill="#b55340"/><circle cx="122" cy="79" r="7" fill="#bd654b"/></svg>',
  rest: '<svg viewBox="0 0 180 140" fill="none" aria-hidden="true"><circle cx="91" cy="71" r="53" stroke="#f9e6b8" stroke-opacity=".4"/><circle cx="91" cy="71" r="40" stroke="#f9e6b8" stroke-opacity=".3"/><path d="M111 30a43 43 0 1 0 29 65A40 40 0 0 1 111 30Z" fill="#f4e4bb"/><path d="m120 47 3 8 8 3-8 3-3 8-3-8-8-3 8-3Z" fill="#433a27"/><circle cx="142" cy="34" r="3" fill="#f4e4bb"/></svg>'
};
function harpexIntroArt(slide) {
  if (slide === 0) return '<div class="intro-stack" aria-hidden="true"><div class="track-card track-food"><small>FIND DIN</small><strong>Energi.</strong>'+HARPEX_ART.food+'</div><div class="track-card track-rest"><small>PLADS TIL</small><strong>Ro.</strong>'+HARPEX_ART.rest+'</div><div class="track-card track-train"><small>BYG DIN</small><strong>Styrke.</strong>'+HARPEX_ART.training+'<span class="track-caption">DIT TEMPO. DIN PLAN. ↗</span></div></div>';
  if (slide === 1) return '<div class="badge-scene" aria-hidden="true"><span class="badge-ghost">01</span><div class="rhythm-badge"><span>HARPEX</span><b>🔥</b><strong>Din rytme</strong><small>ÉN DAG AD GANGEN</small></div><span class="badge-ghost">07</span></div>';
  return '<div class="intro-plan" aria-hidden="true"><div class="intro-plan-top"><span>Din hverdag.<br><strong>Samlet ét sted.</strong></span><b>↗</b></div><div class="intro-plan-body"><span class="example-label">EKSEMPEL PÅ DIN DAG</span><div><span>🏋️</span><span>Giv din træning retning<small>Din personlige styrkeplan</small></span><i>✓</i></div><div><span>🥑</span><span>Find energi til mere<small>Måltider og dine mål</small></span><i></i></div><div><span>🌙</span><span>Gør plads til restitution<small>Søvn, energi og check-in</small></span><i></i></div></div></div>';
}
function harpexIntro(slide) {
  const copy = [
    ['Skab din egen<br><em>rytme.</em>', 'Træning, mad og restitution.<br>Tre spor. Én hverdag. Helt din egen.'],
    ['Små skridt.<br><em>Stærkere vaner.</em>', 'Følg dine pas og mærk din udvikling.<br>Det handler om at blive ved.'],
    ['En plan, der<br><em>følger dig.</em>', 'Tilpas HARPEX til din sport, dine mål<br>og den hverdag, du faktisk har.']
  ][slide];
  return '<div class="onboarding-top intro-top"><button type="button" class="onboarding-back" data-intro-back aria-label="Forrige introduktion" '+(slide===0?'style="visibility:hidden"':'')+'>'+uiIcon('arrow')+'</button><span class="intro-wordmark">HARPEX</span><button type="button" class="text-button" data-onboard="preview">Se appen</button></div><form id="onboardingForm" class="intro-page"><div class="intro-art">'+harpexIntroArt(slide)+'</div><div class="intro-dots" aria-label="Introduktion '+(slide+1)+' af 3">'+[0,1,2].map(i=>'<span class="'+(i===slide?'active':'')+'"></span>').join('')+'</div><h1 id="onboardingTitle" tabindex="-1">'+copy[0]+'</h1><p class="intro-description">'+copy[1]+'</p><div class="intro-bottom"><button type="submit" class="button onboarding-continue">'+(slide===2?'Find min rytme':'Næste')+'<span aria-hidden="true">↗</span></button><p>Kun på din enhed. Ingen konto nødvendig.</p></div></form>';
}
